import { useUser } from "@clerk/nextjs";
import { Spinner } from "@nextui-org/react";
import Head from "next/head";
import React from "react";
import Navbar from "~/components/navbar/Navbar";

interface ProtectedRouteProps {
  title: string;
  children: React.ReactNode;
}

export default function ProtectedRoute({
  title,
  children,
}: ProtectedRouteProps) {
  const { user } = useUser();

  if (!user) {
    return (
      <React.Fragment>
        <Head>
          <title>Loading...</title>
          <meta name="description" content="Loading app..." />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="flex h-screen  w-full items-center justify-center">
          <Spinner size="lg" color="primary" label="Loading..." />
        </div>
      </React.Fragment>
    );
  }

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {children}
    </>
  );
}
